name: Build with CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifactpath: build/objrenderer
          - os: windows-latest
            artifactpath: build/objrenderer.exe
          - os: macos-latest
            artifactpath: build/objrenderer

    steps:
      - name: Setup Environment
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cd ${{ github.workspace }} && cmake --build build/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: objrenderer-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/${{ matrix.artifactpath }}